# Generated by Django 4.1.4 on 2022-12-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TwoNumberSum",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_num", models.IntegerField()),
                ("second_num", models.IntegerField()),
                ("sum", models.IntegerField(null=True)),
            ],
        ),
    ]
